name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Run Unit Tests
      - uses: actions/checkout@v2 
        run: GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: |
          go vet ./...
